### ISSUE TITLE
_fkey_view duplicate table_name

### ISSUE THREAD

**Issue by DanielZavacky** [toluaina/pgsync#116] opened 2021-04-26 10:48 UTC
PGSync version: https://github.com/toluaina/pgsync/commit/77e12b5f81d784f2011cfcb4ee4f40ed405726c9

Postgres version: 13.1

Elasticsearch version: 7.10.1

Redis version: 6.2.1

Python version: 3.7

Problem Description: 
When there is table with two foreign keys pointing to same table, it throws error.
![img](https://user-images.githubusercontent.com/45260819/116070808-55804000-a68d-11eb-929f-8cf1b2f3cd65.jpg)

Error Message (if any): 

```
[SQL: CREATE UNIQUE INDEX fkey_idx ON "custom_logging"."_fkey_view" (table_name)]
DETAIL:  Key (table_name)=(items) is duplicated.
```

**Comment by toluaina** [comment] 2021-04-26 21:11
Thanks. Are you able to provide a more complete example, please? 
e.g schema config, DB schema, or even any logging would help to reproduce quicker

**Comment by DanielZavacky** [comment] 2021-04-27 10:20
Error occurred when running bootstrap.py

<details><summary>schema.json:</summary><p>

```json
[
	{
        "database": "test",
		"index": "group_items",
		"nodes": [
			{
				"table": "group_items",
				"label": "group_items",
				"schema": "public",
				"columns": [
					"id"
                ],
                "children": [
				    {
					    "table": "items",
                        "label": "item_one",
						"columns": [
						    "id"
						],
						"relationship": {
						    "variant": "object",
						    "type": "one_to_one",
                            "foreign_key": {
                                "child": ["id"],
                                "parent": ["itemOneID"]
                            }
                        }
                    },
                    {
					    "table": "items",
                        "label": "item_two",
						"columns": [
						    "id"
						],
						"relationship": {
						    "variant": "object",
						    "type": "one_to_one",
                            "foreign_key": {
                                "child": ["id"],
                                "parent": ["itemTwoID"]
                            }
                        }
                    }
                ]
            }
        ]
    }
]
```
</p></details>
<details><summary>test.sql:</summary><p>

```sql
-- items
DROP TABLE IF EXISTS "public"."items";
CREATE TABLE "public"."items" (
  "id" int4 NOT NULL
);

ALTER TABLE "public"."items" ADD CONSTRAINT "items_pkey" PRIMARY KEY ("id");

-- group_items 
DROP TABLE IF EXISTS "public"."group_items";
CREATE TABLE "public"."group_items" (
  "id" int4 NOT NULL,
  "itemOneID" int4 NOT NULL,
  "itemTwoID" int4 NOT NULL
);

ALTER TABLE "public"."group_items" ADD CONSTRAINT "group_items_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."group_items" ADD CONSTRAINT "group_items_itemOneID_fkey" FOREIGN KEY ("itemOneID") REFERENCES "public"."items" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."group_items" ADD CONSTRAINT "group_items_itemTwoID_fkey" FOREIGN KEY ("itemTwoID") REFERENCES "public"."items" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
```
</p></details>
<details><summary>tracelog of error:</summary><p>

```
Traceback (most recent call last):
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: could not create unique index "fkey_idx"
DETAIL:  Key (table_name)=(items) is duplicated.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\bin\bootstrap", line 68, in <module>
    main()
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\bin\bootstrap", line 63, in main
    sync.setup()
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\pgsync\sync.py", line 166, in setup
    self.create_views(schema, tables, user_defined_fkey_tables)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\pgsync\base.py", line 620, in create_views
    self.__engine.execute(
  File "<string>", line 2, in execute
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 3037, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\sql\ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1290, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\zavo66\workspace\VisualStudioCode\python\pgsync\venv\lib\site-packages\sqlalchemy\engine\default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) could not create unique index "fkey_idx"
DETAIL:  Key (table_name)=(items) is duplicated.

[SQL: CREATE UNIQUE INDEX fkey_idx ON "custom_logging"."_fkey_view" (table_name)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
```
</p></details>

**Comment by abdheshkumar** [comment] 2021-04-27 14:58
@toluaina I am also getting the same issue.

**Comment by martinhogf** [comment] 2021-04-27 20:58
@toluaina I caught the same problem. Same scenario.

**Comment by abdheshkumar** [comment] 2021-04-27 23:28
> @toluaina I am also getting the same issue but below is another issue. It is not able to run more than one nodes.
> Here is the schema file
> 
> 
 I am trying to put two independent tables data into a single index but it is synching only the data of the first table which means it is moving `pm_ptflio_bld_blck_grp` data into `portfolio_clusters` index and there is no data in the index for `pm_ptflio_bld_blck` table.
> [
>   {
>     "database": "productstoredb",
>     "index": "portfolio_clusters",
>     "nodes": [
>       {
>         "table": "pm_ptflio_bld_blck_grp",
>         "schema": "product_store",
>         "columns": [
>           "ptflio_bld_blck_grp_mstr_key",
>           "ptflio_bld_blck_grp_nm"
>         ]
>       },
>       {
>         "table": "pm_ptflio_bld_blck",
>         "schema": "product_store",
>         "columns": [
>           "ptflio_bld_blck_mstr_key",
>           "ptflio_bld_blck_nm"
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> Here are a log pgsync logs
> 
> ```
> - pm_ptflio_bld_blck_grp
> - pm_ptflio_bld_blck_grp
>  [==================================================] 100.0%
> ```
> 
> The log should display like
> 
> ```
> - pm_ptflio_bld_blck_grp
> - pm_ptflio_bld_blck
>  [==================================================] 100.0%
> ```

**Comment by abdheshkumar** [comment] 2021-04-27 23:30
I also notice another issue, when you provide elasticsearch settings with schema.json it doesn't create elasticsearch settings.

**Comment by abdheshkumar** [comment] 2021-04-27 23:52
I tried to run a book example but it did not work.

```
wait-for-it.sh: waiting 60 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
wait-for-it.sh: waiting 60 seconds for elasticsearch:9200
wait-for-it.sh: elasticsearch:9200 is available after 0 seconds
wait-for-it.sh: waiting 60 seconds for redis:6379
wait-for-it.sh: redis:6379 is available after 0 seconds
2021-04-27 23:44:40.864:WARNING:pgsync.helper: Database "book" does not exist: (psycopg2.OperationalError) FATAL:  database "book" does not exist

(Background on this error at: http://sqlalche.me/e/14/e3q8)
2021-04-27 23:44:41,049 INFO sqlalchemy.engine.Engine select version()
2021-04-27 23:44:41,049 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,050 INFO sqlalchemy.engine.Engine select current_schema()
2021-04-27 23:44:41,050 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,051 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2021-04-27 23:44:41,051 INFO sqlalchemy.engine.Engine [raw sql] {}
2021-04-27 23:44:41,053 INFO sqlalchemy.engine.Engine CREATE EXTENSION IF NOT EXISTS "POSTGIS"
2021-04-27 23:44:41,053 INFO sqlalchemy.engine.Engine [raw sql] (None,)
2021-04-27 23:44:41,054 INFO sqlalchemy.engine.Engine ROLLBACK using DBAPI connection.rollback(), DBAPI should ignore due to autocommit mode
2021-04-27 23:44:41.054:ERROR:pgsync.base: Exception (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgr
esql/extension/POSTGIS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/local/share/postgresql/extension/POSTGIS.control": No such file or direc
tory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1084, in pg_execute
    conn.execute(query, values)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1190, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgresql/extension/POSTG
IS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/local/share/postgresql/extension/POSTGIS.control": No such file or direc
tory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/book/schema.py", line 275, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "examples/book/schema.py", line 271, in main
    setup(config)
  File "examples/book/schema.py", line 248, in setup
    create_extension(database, 'POSTGIS', echo=True)
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1117, in create_extension
    pg_execute(engine, f'CREATE EXTENSION IF NOT EXISTS "{extension}"')
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 1084, in pg_execute
    conn.execute(query, values)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1190, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/local/share/postgresql/extension/POSTG
IS.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS "POSTGIS"]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extras.py", line 1292, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "public.continent" does not exist
LINE 1: INSERT INTO public.continent (name) VALUES ('Europe'),('Nort...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/book/data.py", line 501, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "examples/book/data.py", line 64, in main
    session.add_all(continents.values())
  File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 952, in __exit__
    self.session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3255, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3395, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3355, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 247, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1154, in _emit_insert_statements
    statement, multiparams, execution_options=execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 909, in do_executemany
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extras.py", line 1292, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "public.continent" does not exist
LINE 1: INSERT INTO public.continent (name) VALUES ('Europe'),('Nort...
                    ^

[SQL: INSERT INTO public.continent (name) VALUES (%(name)s) RETURNING public.continent.id]
[parameters: ({'name': 'Europe'}, {'name': 'North America'})]
(Background on this error at: http://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 59, in main
    sync = Sync(document, verbose=verbose, **params)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 88, in validate
    self._plugins = Plugins('plugins', self.plugins)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 26, in __init__
    self.reload()
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 33, in reload
    self.walk(self.package)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 38, in walk
    plugins = importlib.import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
 0:00:00.023201 (0.02 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1051, in main
    params=params,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 80, in __init__
    self.validate()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 88, in validate
    self._plugins = Plugins('plugins', self.plugins)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 26, in __init__
    self.reload()
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 33, in reload
    self.walk(self.package)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 38, in walk
    plugins = importlib.import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

`runserver.sh`
```
#! /bin/sh
./wait-for-it.sh postgres:5432 -t 60
./wait-for-it.sh elasticsearch:9200 -t 60
./wait-for-it.sh redis:6379 -t 60

python examples/book/schema.py --config examples/book/schema.json
python examples/book/data.py --config examples/book/schema.json

bootstrap --config examples/book/schema.json
pgsync --config examples/book/schema.json --daemon
```

**Comment by toluaina** [comment] 2021-04-28 11:41
@martinhogf @DanielZavacky 

This issue has now been resolved in master. Can you try and let me know

**Comment by toluaina** [comment] 2021-04-28 11:43
@abdheshkumar Would you mind please raising this in a separate issue. so we can track them separately.  
This one will be closed soon

**Comment by DanielZavacky** [comment] 2021-04-28 12:48
@toluaina It works in master. Thank you

**Comment by martinhogf** [comment] 2021-04-30 14:39
Hi @toluaina , sorry for the delay but I was solving some very critical things.

Apparently it's working.

Thanks.

**Comment by toluaina** [comment] 2021-05-03 12:38
Thanks. Closing this now.

**Comment by DanielZavacky** [comment] 2021-05-04 12:32
@toluaina Hi. I was testing it again on more complex schema and it does not work properly. I made fork from this repo (with newest commits) where I created shop example [pgsync_fork](https://github.com/DanielZavacky/pgsync/tree/fkey_view_duplicated_table_name). It is on fkey_view_duplicated_table_name branch. Just run bootstrap and you will see error: `Key (table_name)=(renters) is duplicated.`. 
Error occures when there is foreign_key property specified in relationship in schema.json and table for which it is specified has another foreign keys.
In my case I have table renter, which is used in service_product_category_renter table as foreign key and renter table has createdBy column which is foreign key to user table. It will create two rows for renter table and then it want to create unique index on table_name
![renter_schema](https://user-images.githubusercontent.com/45260819/117003306-fb165d80-ace4-11eb-8a67-67a0f75be99c.jpg)
![fkey_view](https://user-images.githubusercontent.com/45260819/117003328-02d60200-ace5-11eb-89cf-aca8b3dcf29c.jpg)

**Comment by DanielZavacky** [comment] 2021-05-07 21:32
@toluaina It does not throw error anymore, but I am not sure if it creates correct foreign keys data. My understanding of _fkey_view_ is, that it should store foreign keys of tables. But for example, when I have schema where I specify _foreign_key_ property in _renterOne_ node:
![schema_example](https://user-images.githubusercontent.com/45260819/117509526-ad228380-af8a-11eb-9341-c9b3c0243723.jpg),
I get those foreign keys:
![fkey_view](https://user-images.githubusercontent.com/45260819/117509693-fd99e100-af8a-11eb-9c4e-907e8ce927a6.jpg).
Should not **renters** table have only **createdBy** foreign key since it is the only real foreign key in this table? **id** is not foreign key and **renterOneID**/**renterTwoID** are foreign keys in **service_product_category_renters** (where they are correctly added)

**Comment by toluaina** [comment] 2021-05-10 10:36
@DanielZavacky 
This is normal and the expected behaviour. I tried explaining this in a different thread somewhere and the reason is partially expressed in the the code comments. I will try to finish the technical document for pgsync someday. But in the mean time this is how it should behave. 

We don't specify the direction of the foreign keys in the config. Since we want to keep things simple. So we need to include both foreign and primary as possible candidates for foreign key.

**Comment by toluaina** [comment] 2021-05-15 13:40
This has now been resolved. thanks

**Closed by toluaina** 2021-05-15 13:40 UTC
