### ISSUE TITLE
SSL SYSCALL error

### ISSUE THREAD

**Issue by smokedsalmonbagel** [toluaina/pgsync#68] opened 2021-02-01 18:53 UTC
PGSync version: 
1.1.25
Postgres version: 
9.6.18
Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
After several minutes of polling the DB pgsync gives this error.  I tried setting the poll_timeout env var in my docker-compose.yml:
```
- POLL_TIMEOUT=5
```
Maybe there should be some retry code added?  I also noticed the connection is not retried if the database is disconnected for a bit.

Error Message (if any): 

```
pgsync_1         | Polling db mydb: 0 cache items
pgsync_1         | Exception in thread Thread-8:
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
pgsync_1         |     self.run()
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
pgsync_1         |     self._target(*self._args, **self._kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 816, in poll_db
pgsync_1         |     conn.poll()
pgsync_1         | psycopg2.OperationalError: SSL SYSCALL error: EOF detected
pgsync_1         | 
pgsync_1         | 
pgsync_1         | 2021-02-01 17:26:19.695:ERROR:sqlalchemy.pool.impl.QueuePool: Exception during reset or similar
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
pgsync_1         |     fairy._reset(pool)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
pgsync_1         |     pool._dialect.do_rollback(self)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
pgsync_1         |     dbapi_connection.rollback()
pgsync_1         | psycopg2.InterfaceError: connection already closed
pgsync_1         | 2021-02-01 17:51:47.246:DEBUG:pgsync.sync: Truncating replication slot: mydb_amenities
pgsync_1         | 2021-02-01 17:51:47.250:ERROR:pgsync.base: Exception (psycopg2.OperationalError) SSL SYSCALL error: EOF detected


```

**Comment by toluaina** [comment] 2021-02-01 20:01
This has been reported before but I was unable to get more information get to the bottom of it.
I have seen reports of this on AWS.

Do you have access to the logs? 
- Can you search for the "terminating walsender process due to replication timeout" in the logs around the time the error occured
- or any other clues around the time this error occurred

**Comment by smokedsalmonbagel** [comment] 2021-02-01 20:53
Nothing too striking here - looks like the connection went away from the client side.  I'm going to keep digging.  Here is part of our log in the meantime:
```
2021-02-01 18:00:11 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:00:11 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.126 s, sync=0.002 s, total=0.141 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16383 kB, estimate=16390 kB
2021-02-01 18:05:11 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:05:11 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.126 s, sync=0.002 s, total=0.139 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16390 kB
2021-02-01 18:10:12 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:10:12 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.127 s, sync=0.001 s, total=0.139 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16389 kB
2021-02-01 18:15:12 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:15:12 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.126 s, sync=0.001 s, total=0.140 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16388 kB
2021-02-01 18:20:12 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:20:12 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.127 s, sync=0.002 s, total=0.142 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16388 kB
2021-02-01 18:25:12 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:25:12 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.126 s, sync=0.001 s, total=0.139 s; sync files=1, longest=0.001 s, average=0.001 s; distance=16384 kB, estimate=16387 kB
2021-02-01 18:30:12 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:30:12 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.127 s, sync=0.002 s, total=0.140 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16387 kB
2021-02-01 18:35:13 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:35:13 UTC::@:[12345]:LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.125 s, sync=0.002 s, total=0.139 s; sync files=1, longest=0.002 s, average=0.002 s; distance=16384 kB, estimate=16387 kB
2021-02-01 18:38:38 UTC:10.0.4.103(61220):myuser@mydb:[32406]:LOG:  logical decoding found consistent point at 7C9/87008368
2021-02-01 18:38:38 UTC:10.0.4.103(61220):myuser@mydb:[32406]:DETAIL:  There are no running transactions.
2021-02-01 18:38:38 UTC:10.0.4.103(61220):myuser@mydb:[32406]:STATEMENT:  SELECT * 
	FROM PG_CREATE_LOGICAL_REPLICATION_SLOT('mydb_amenities', 'test_decoding')
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:LOG:  starting logical decoding for slot "mydb_amenities"
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:DETAIL:  streaming transactions committing after 7C9/870083A0, reading WAL from 7C9/87008368
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:STATEMENT:  SELECT xid, data 
	FROM PG_LOGICAL_SLOT_PEEK_CHANGES('mydb_amenities', NULL, NULL) 
	WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < 227800
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:LOG:  logical decoding found consistent point at 7C9/87008368
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:DETAIL:  There are no running transactions.
2021-02-01 18:39:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:STATEMENT:  SELECT xid, data 
	FROM PG_LOGICAL_SLOT_PEEK_CHANGES('mydb_amenities', NULL, NULL) 
	WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < 227800
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:LOG:  starting logical decoding for slot "mydb_amenities"
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:DETAIL:  streaming transactions committing after 7C9/870083A0, reading WAL from 7C9/870083A0
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:STATEMENT:  SELECT xid, data 
	FROM PG_LOGICAL_SLOT_PEEK_CHANGES('mydb_amenities', NULL, NULL) 
	WHERE CAST(CAST(xid AS TEXT) AS BIGINT) >= 227800 AND CAST(CAST(xid AS TEXT) AS BIGINT) < 227801
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:LOG:  logical decoding found consistent point at 7C9/870083A0
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:DETAIL:  There are no running transactions.
2021-02-01 18:39:26 UTC:10.0.4.103(61228):myuser@mydb:[1573]:STATEMENT:  SELECT xid, data 
	FROM PG_LOGICAL_SLOT_PEEK_CHANGES('mydb_amenities', NULL, NULL) 
	WHERE CAST(CAST(xid AS TEXT) AS BIGINT) >= 227800 AND CAST(CAST(xid AS TEXT) AS BIGINT) < 227801
2021-02-01 18:40:13 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:40:14 UTC::@:[12345]:LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.831 s, sync=0.002 s, total=0.845 s; sync files=7, longest=0.002 s, average=0.000 s; distance=16417 kB, estimate=16417 kB
2021-02-01 18:45:13 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:45:13 UTC::@:[12345]:LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.329 s, sync=0.004 s, total=0.343 s; sync files=3, longest=0.004 s, average=0.001 s; distance=16353 kB, estimate=16411 kB
2021-02-01 18:45:25 UTC:10.0.4.103(61228):myuser@mydb:[1573]:LOG:  could not receive data from client: Connection reset by peer
2021-02-01 18:45:25 UTC:10.0.4.103(61222):myuser@mydb:[960]:LOG:  could not receive data from client: Connection reset by peer
2021-02-01 18:49:51 UTC:10.0.4.103(61327):[unknown]@[unknown]:[10163]:LOG:  PID 25748 in cancel request did not match any process
2021-02-01 18:50:13 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:50:13 UTC::@:[12345]:LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.326 s, sync=0.001 s, total=0.338 s; sync files=3, longest=0.001 s, average=0.000 s; distance=16384 kB, estimate=16408 kB
2021-02-01 18:55:13 UTC::@:[12345]:LOG:  checkpoint starting: time
2021-02-01 18:55:14 UTC::@:[12345]:LOG:  checkpoint complete: wrote 5 buffers (0.0%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.527 s, sync=0.002 s, total=0.541 s; sync files=5, longest=0.002 s, average=0.000 s; distance=16392 kB, estimate=16406 kB
```

**Comment by smokedsalmonbagel** [comment] 2021-02-02 20:40
A few updates

- I tried to set wal_sender_timeout to 0 on the server (default is 30 I think)
- It seems each time this happens it is always 5 minutes after the inital sync.
- I reverted back to using the default POLL_TIMEOUT

**Comment by toluaina** [comment] 2021-02-02 22:10
- `POLL_TIMEOUT` does have a direct impact on CPU utilization. Tune this to get closer to real-time
- Can you let me know if this is still happening?
- Looking at [this thread](https://forums.aws.amazon.com/thread.jspa?threadID=233810) I wonder if this has something to do with Postgres 9.x 
- Do you have the luxury of upgrading from Postgres 9.x?

**Comment by smokedsalmonbagel** [comment] 2021-02-02 22:29
Good to know when I do more load testing.

I saw that thread - we are on 9.6 but they mentioned 9.4, but it also sounded like maybe it could affect other versions. I think 'ssl_renegotiation_limit' is not an option > 9.5 - it is not configurable for us.

I think they are actually retiring 9.6 on AWS soon so the plan right now is to migrate (quite a coincidence ) maybe this week.
I will keep you updated.

One more question - if this issue is solved and the database connection is dropped due to say a network outage will pgsync currently re establish the connection?

**Comment by toluaina** [comment] 2021-02-03 19:46
I'm afraid PGSync will not attempt to re-establish a connection. This needs to happen at a different layer. You can look into pgbouncer for this. I have used it in the past and it is very robust. https://www.pgbouncer.org/

PGSync will ensure that the data is transactionally consistent. So even if connections are dropped and you restart, you will not lose data.

**Comment by toluaina** [comment] 2021-02-03 22:12
If you are getting this error frequently:
Can you please try these Postgres config parameters and values:
```
tcp_keepalives_idle: 60
tcp_keepalives_interval: 60
tcp_keepalives_count: 100 
```

**Comment by smokedsalmonbagel** [comment] 2021-02-04 20:27
We were able to upgrade yesterday to postgres 10.15.  Still seeing the same issue.  It looks like the error occurs 5 minutes after the last DB transaction.  If I make some inserts into our table the error will occur 5 minutes after the last insert I made.  I will take a look at our config vars as listed above and give it a try.

Good to know about pgbouncer.  Shouldn't pgsync exit on error in a child thread so that the container exits?  Right now when this error happens pgsync container stays up but is not syncing.  It continues to use cpu.  This seems like a problematic condition.

**Comment by toluaina** [comment] 2021-02-04 22:29
I am still doing some research on the cause of this. 

You are right pgsync should exit on an operational error. I have pushed some changes to master to address this

**Comment by smokedsalmonbagel** [comment] 2021-02-04 23:37
A few more notes:

- I am using a VPN to connect to a private network with our RDS
- I deployed pgbouncer and after 5 minutes got ```2021-02-04 22:47:07.499 UTC [1] LOG S-0x7fa2ecb85350: db/user@ip:port closing because: server conn crashed? (age=404s)``` in session pool_mode
- In transaction pool_mode I get warnings and DB changes don't get replicated (I probably am just missing something in the config for pool_mode here)

**Comment by smokedsalmonbagel** [comment] 2021-02-06 20:06
I have an AWS RDS test environment setup where I can experiment with different config variables etc.  I have tried ```idle_in_transaction_session_timeout``` and ```wal_sender_timeout```.  If you have any tests / logs you want to run let me know.  This is the server log when the error occurs:
```
2021-02-06 20:04:03 UTC::@:[8589]:LOG: checkpoint starting: time
2021-02-06 20:04:04 UTC::@:[8589]:LOG: checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.403 s, sync=0.002 s, total=0.416 s; sync files=4, longest=0.002 s, average=0.000 s; distance=16373 kB, estimate=16373 kB
############# pgsync error here  
2021-02-06 20:04:33 UTC::@:[8589]:LOG: checkpoint starting: time
2021-02-06 20:04:33 UTC::@:[8589]:LOG: checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.302 s, sync=0.002 s, total=0.313 s; sync files=3, longest=0.002 s, average=0.000 s; distance=11 kB, estimate=14736 kB
2021-02-06 20:05:03 UTC::@:[8589]:LOG: checkpoint starting: time
2021-02-06 20:05:03 UTC::@:[8589]:LOG: checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.403 s, sync=0.002 s, total=0.414 s; sync files=3, longest=0.002 s, average=0.000 s; distance=20 kB, estimate=13265 kB
```

**Comment by smokedsalmonbagel** [comment] 2021-02-08 21:40
Yes, docker-compose on Mac.  I also just gave it a try on docker-compose in Windows with the same results.

**Comment by smokedsalmonbagel** [comment] 2021-02-09 20:45
I was looking at the other issues [this thread](https://github.com/docker/for-mac/issues/3679#issuecomment-642885218) and [61](https://github.com/toluaina/pgsync/issues/61) which was showing the same message.  Tried using the suggested sysctls and it seems to have worked:
```
    sysctls:
        - net.ipv4.tcp_keepalive_time=200
        - net.ipv4.tcp_keepalive_intvl=200
        - net.ipv4.tcp_keepalive_probes=5 
```

Going to keep testing before I close this but it is looking promising so far.

**Comment by toluaina** [comment] 2021-02-09 22:09
that's amazing! let me know if that resolves it.

**Comment by smokedsalmonbagel** [comment] 2021-02-10 16:58
I think this is resolved.  I have been connected to two different AWS RDS instances for several hours.

**Comment by toluaina** [comment] 2021-02-11 19:07
Thanks for debugging this. I will add these options to the docker-compose file

**Comment by toluaina** [comment] 2021-02-11 21:16
Closing this

**Closed by toluaina** 2021-02-11 21:16 UTC
